/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2014-01-24 07:26:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.multicampus.biz.board.impl.BoardDAO;
import com.multicampus.biz.board.vo.BoardVO;

public final class getBoardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 1. 사용자 입력정보(검색 정보) 추출
	request.setCharacterEncoding("euc-kr");
	String searchCondition = request.getParameter("searchCondition");
	String searchKeyword = request.getParameter("searchKeyword");
	
	// Null Check
	if(searchCondition == null) searchCondition = "TITLE";
	if(searchKeyword == null) searchKeyword = "";
	
	// 2. DB 연동
	BoardVO vo = new BoardVO();
	vo.setSearchCondition(searchCondition);
	vo.setSearchKeyword(searchKeyword);
	
	BoardDAO boardDAO = new BoardDAO();
	List<BoardVO> boardList = boardDAO.getBoardList(vo);
	
	// 3. 결과 화면 구성

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>글 목록</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<h1>글 목록</h1>\r\n");
      out.write("<h3>test님 로그인 환영합니다......\r\n");
      out.write("<a href=\"logout_proc.jsp\">Log-out</a></h3>\r\n");
      out.write("\r\n");
      out.write("<!-- 검색 시작 -->\r\n");
      out.write("<form action=\"getBoardList.jsp\" method=\"post\">\r\n");
      out.write("\t<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" width=\"700\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t<select name=\"searchCondition\">\r\n");
      out.write("\t\t\t<option value=\"TITLE\">제목\r\n");
      out.write("\t\t\t<option value=\"CONTENT\">내용\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input name=\"searchKeyword\" type=\"text\"/>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"검색\"/>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- 검색 종료 -->\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" width=\"700\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th bgcolor=\"orange\" width=\"100\">번호</th>\r\n");
      out.write("\t<th bgcolor=\"orange\" width=\"200\">제목</th>\r\n");
      out.write("\t<th bgcolor=\"orange\" width=\"150\">작성자</th>\r\n");
      out.write("\t<th bgcolor=\"orange\" width=\"150\">등록일</th>\r\n");
      out.write("\t<th bgcolor=\"orange\" width=\"100\">조회수</th>\r\n");
      out.write("</tr>\r\n");

	for(BoardVO board : boardList) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>");
      out.print( board.getSeq() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"left\"><a href=\"getBoard.jsp?seq=");
      out.print( board.getSeq() );
      out.write('"');
      out.write('>');
      out.print( board.getTitle() );
      out.write("</a></td>\r\n");
      out.write("\t<td>");
      out.print( board.getWriter() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print( board.getRegDate() );
      out.write("</td>\r\n");
      out.write("\t<td>");
      out.print( board.getCnt() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<a href=\"addBoard.jsp\">새글 등록</a>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
